# Generated by Django 5.2 on 2025-05-16 04:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('qty_ordered', models.IntegerField(blank=True, null=True)),
                ('qty_received', models.IntegerField(blank=True, null=True)),
                ('quantity_installed', models.IntegerField(blank=True, null=True)),
                ('quantity_available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, default='invited', max_length=50)),
                ('password', models.BinaryField()),
            ],
            options={
                'db_table': 'invited_users',
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_selected', models.TextField(blank=True, null=True)),
                ('supplier', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_data',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_number', models.IntegerField(unique=True)),
                ('prompt_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('king', models.TextField(blank=True, null=True)),
                ('double', models.TextField(blank=True, null=True)),
                ('exec_king', models.TextField(blank=True, null=True)),
                ('bath_screen', models.TextField(blank=True, null=True)),
                ('room_model', models.TextField(blank=True, null=True)),
                ('left_desk', models.TextField(blank=True, null=True)),
                ('right_desk', models.TextField(blank=True, null=True)),
                ('to_be_renovated', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_data',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_model', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_model',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('production_starts', models.DateField(blank=True, null=True)),
                ('production_ends', models.DateField(blank=True, null=True)),
                ('shipping_depature', models.DateField(blank=True, null=True)),
                ('shipping_arrival', models.DateField(blank=True, null=True)),
                ('custom_clearing_starts', models.DateField(blank=True, null=True)),
                ('custom_clearing_ends', models.DateField(blank=True, null=True)),
                ('arrive_on_site', models.DateField(blank=True, null=True)),
                ('pre_work_starts', models.DateField(blank=True, null=True)),
                ('pre_work_ends', models.DateField(blank=True, null=True)),
                ('install_starts', models.DateField(blank=True, null=True)),
                ('install_ends', models.DateField(blank=True, null=True)),
                ('post_work_starts', models.DateField(blank=True, null=True)),
                ('post_work_ends', models.DateField(blank=True, null=True)),
                ('floor_completed', models.DateField(blank=True, null=True)),
                ('floor_closes', models.DateField(blank=True, null=True)),
                ('floor_opens', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='hotel_bot_app.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField()),
                ('received_qty', models.PositiveIntegerField()),
                ('damaged_qty', models.PositiveIntegerField()),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'inventory_received',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('product_available', models.TextField(blank=True, null=True)),
                ('prework', models.TextField(blank=True, null=True)),
                ('prework_check_on', models.DateTimeField(blank=True, null=True)),
                ('install', models.TextField(blank=True, null=True)),
                ('post_work', models.TextField(blank=True, null=True)),
                ('post_work_check_on', models.DateTimeField(blank=True, null=True)),
                ('day_install_began', models.DateTimeField(blank=True, null=True)),
                ('day_install_complete', models.DateTimeField(blank=True, null=True)),
                ('product_arrived_at_floor', models.TextField(blank=True, null=True)),
                ('product_arrived_at_floor_check_on', models.DateTimeField(blank=True, null=True)),
                ('retouching', models.TextField(blank=True, null=True)),
                ('retouching_check_on', models.DateTimeField(blank=True, null=True)),
                ('post_work_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_work_checked_by', to='hotel_bot_app.inviteduser')),
                ('prework_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prework_checked_by', to='hotel_bot_app.inviteduser')),
                ('product_arrived_at_floor_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_arrived_checked_by', to='hotel_bot_app.inviteduser')),
                ('retouching_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retouching_checked_by', to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'install',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close'), ('PENDING', 'Pending'), ('WORKING', 'Working')], default='OPEN', max_length=10)),
                ('type', models.CharField(choices=[('ROOM', 'Room'), ('FLOOR', 'Floor'), ('PRODUCT', 'Product'), ('OTHER', 'Other')], max_length=10)),
                ('is_for_hotel_owner', models.BooleanField(default=False)),
                ('related_floors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of floor numbers', null=True, size=None)),
                ('other_type_details', models.TextField(blank=True, null=True, verbose_name='Other Details')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='hotel_bot_app.inviteduser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_issues', to='hotel_bot_app.inviteduser')),
                ('observers', models.ManyToManyField(blank=True, related_name='observed_issues', to='hotel_bot_app.inviteduser')),
                ('related_product', models.ManyToManyField(blank=True, related_name='issues', to='hotel_bot_app.productdata', verbose_name='Related Product Items')),
                ('related_rooms', models.ManyToManyField(blank=True, related_name='issues', to='hotel_bot_app.roomdata', verbose_name='Related Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text_content', models.TextField(blank=True, null=True)),
                ('media', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel_bot_app.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PullInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('available_qty', models.PositiveIntegerField(default=0)),
                ('pulled_date', models.DateField(blank=True, null=True)),
                ('qty_pulled', models.PositiveIntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('qty_available_after_pull', models.PositiveIntegerField(default=0)),
                ('pulled_by', models.ForeignKey(blank=True, db_column='checked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'pull_inventory',
            },
        ),
        migrations.AddField(
            model_name='roomdata',
            name='room_model_id',
            field=models.ForeignKey(blank=True, db_column='room_model_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.roommodel'),
        ),
        migrations.CreateModel(
            name='ProductRoomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.productdata')),
                ('room_model_id', models.ForeignKey(blank=True, db_column='room_model_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.roommodel')),
            ],
            options={
                'db_table': 'product_room_model',
            },
        ),
        migrations.CreateModel(
            name='InstallDetail',
            fields=[
                ('install_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('installed_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.TextField(default='NO')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_details', to='hotel_bot_app.installation')),
                ('installed_by', models.ForeignKey(blank=True, db_column='installed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.productdata')),
                ('room_id', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.roomdata')),
                ('room_model_id', models.ForeignKey(blank=True, db_column='room_model_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.roommodel')),
            ],
            options={
                'db_table': 'install_detail',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('ship_date', models.DateField()),
                ('ship_qty', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=255)),
                ('bol', models.CharField(max_length=100, unique=True, verbose_name='Bill of Lading')),
                ('expected_arrival_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('checked_by', models.ForeignKey(blank=True, db_column='checked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
    ]
