# Generated by Django 5.2 on 2025-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceived',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='status',
            field=models.CharField(blank=True, default='activated', max_length=50),
        ),
    ]
