# Generated by Django 5.2 on 2025-06-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0003_inventory_hotel_warehouse_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelWarehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=255)),
                ('client_item', models.CharField(max_length=255)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'hotel_warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('client_item', models.CharField(max_length=255)),
                ('quantity_requested', models.PositiveIntegerField(default=0)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_sent', models.PositiveIntegerField(default=0)),
                ('sent', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'warehouse_request',
            },
        ),
    ]
