# Generated by Django 5.2 on 2025-06-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0004_hotelwarehouse_warehouserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelwarehouse',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser'),
        ),
        migrations.AddField(
            model_name='hotelwarehouse',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
