# Generated by Django 5.2 on 2025-06-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0006_roomdata_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdata',
            name='double',
        ),
        migrations.RemoveField(
            model_name='roomdata',
            name='exec_king',
        ),
        migrations.RemoveField(
            model_name='roomdata',
            name='king',
        ),
    ]
