# Generated by Django 5.2 on 2025-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0007_remove_roomdata_double_remove_roomdata_exec_king_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_shipped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
