# Generated by Django 5.2 on 2025-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0008_inventory_quantity_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='floor_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
