# Generated by Django 5.2 on 2025-06-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0009_inventory_floor_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='hotel_bot_app.inviteduser'),
        ),
    ]
