# Generated by Django 5.2 on 2025-06-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0010_warehouserequest_received_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('ship_date', models.DateField()),
                ('ship_qty', models.PositiveIntegerField()),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('expected_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.inviteduser')),
            ],
            options={
                'db_table': 'warehouse_shipment',
            },
        ),
    ]
