# Generated by Django 5.2 on 2025-06-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0011_warehouseshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseshipment',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
    ]
