# Generated by Django 5.2 on 2025-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0012_alter_warehouseshipment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelwarehouse',
            name='damaged_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
