# Generated by Django 5.2 on 2025-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0013_hotelwarehouse_damaged_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='damaged_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='damaged_quantity_at_hotel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='received_at_hotel_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shipped_to_hotel_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
