# Generated by Django 5.2 on 2025-06-20 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0014_inventory_damaged_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserequest',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to='hotel_bot_app.inviteduser'),
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
