# Generated by Django 5.2 on 2025-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0015_warehouserequest_sent_by_warehouserequest_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
