# Generated by Django 5.2 on 2025-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
